modLoader = "javafml"
loaderVersion = "[36,)"
#issueTrackerURL = ""
license = "LGPLv2.1"

[[mods]]
modId = "multiofflinefix"
version = "${version}"
displayName = "MultiOfflineFix Mod"
displayURL = "https://github.com/MCTeamPotato/MultiOfflineFix"
authors = "MCTeampotato, Awei"
description = '''
Fix the issue where offline mode players cannot join multiplayer games
'''
logoFile = "icon.png"

[[dependencies.multiofflinefix]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"


[[dependencies.multiofflinefix]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.multiofflinefix]]
modId = "architectury"
mandatory = true
versionRange = "[1,)"
ordering = "AFTER"
side = "BOTH"